### ISSUE TITLE
AWS Explorer Tool Unable to configure China Region

### ISSUE THREAD

**Issue by demosunguohua** [awsdocs/aws-toolkit-jetbrains-user-guide#1]
I didn't find China region in AWS Connection setting

**Comment by joshbean** [comment]
Closing this issue or pull request in advance of archiving this repo. For more information about the decision to archive this repo (and others in the 'awsdocs' org), see [the announcement on the AWS News Blog](https://aws.amazon.com/blogs/aws/retiring-the-aws-documentation-on-github/).
