### ISSUE TITLE
Creating AWS Lambda

### ISSUE THREAD

**Issue by sakkammadam** [awsdocs/aws-toolkit-jetbrains-user-guide#3]
Team - 
 I am trying to creating an AWS Lambda on its own using PyCharm's AWS tool kit. I have verified that I can connect with my credentials. I wrote a simple script with a lamdba_handler in it and tried to create a lambda function out of it.
 When I try to create - I get a SAM build command failed error message.
On another note, I followed AWS SAM Hello World template and I was able to successfully create a lambda function.

Does this mean I have to create a AWS Serverless application project to create a standalone lambda function ?
The document - https://docs.aws.amazon.com/toolkit-for-jetbrains/latest/userguide/create-new-lambda.html - says otherwise.

Thanks,
Sooraj

**Comment by joshbean** [comment]
Closing this issue or pull request in advance of archiving this repo. For more information about the decision to archive this repo (and others in the 'awsdocs' org), see [the announcement on the AWS News Blog](https://aws.amazon.com/blogs/aws/retiring-the-aws-documentation-on-github/).
