### ISSUE TITLE
Unable to edit the code of lambda

### ISSUE THREAD

**Issue by smaridataai** [awsdocs/aws-toolkit-jetbrains-user-guide#5]
I have connected the pycharm to AWS lambda and I can create new AWS serverless applications and I can deploy them, but I get the problem with editing the code,
Scenario:
When I go the explorer and click on 'Lambda' it does show all the lambda functions, so if I click on any function, right click on it and then click on "Update Function Code" and show up with a pop up, where I need to input a handler name in 'Configuration Settings', which I lookup in AWS and find the handler name but it keep complaining with a small error saying "Must be able to locate the handler in the project in order to deploy to Lambda"
my lambda name is "test_milad" and its inside a directory called "test_milad" and then there is file called "lambda_function.py" and it has a handler and only code which is named a
<img width="853" alt="Screenshot 2022-12-01 at 10 26 55" src="https://user-images.githubusercontent.com/119581585/205016327-addfe4d1-7b1b-4b59-83b4-fc5ccaf45d02.png">
s "lambda_handler",
so my handler is "lambda_function.lambda_handler" as I can see it in AWS console but still I keep getting same error and I can not edit it. 
I tried different formats like "lambda_functions::lambda_handler", "test_milad.lambda_handler", "test_milad.lambda_functions.lambda_handler" or putting slashes etc it's the same. Any guidance would be appreciated.
I followed the installation guidelines from "https://aws.amazon.com/pycharm/"
Details:
Mac OS Monterey 12.6.1 (21G217)
PyCharm 2022.2.4 (Professional Edition)
AWS toolkit version: 1.54-222

**Comment by joshbean** [comment]
Closing this issue or pull request in advance of archiving this repo. For more information about the decision to archive this repo (and others in the 'awsdocs' org), see [the announcement on the AWS News Blog](https://aws.amazon.com/blogs/aws/retiring-the-aws-documentation-on-github/).
